import { Mongo } from 'meteor/mongo';

/**
 * Tasks Collection
 *
 * Document shape:
 * {
 *   _id:       String   — auto-generated by Mongo
 *   text:      String   — the task description
 *   checked:   Boolean  — whether the task is completed
 *   category:  String   — one of CATEGORIES keys (Work, Personal, Urgent, Other)
 *   order:     Number   — sort order for drag-and-drop (lower = higher in list)
 *   createdAt: Date     — creation timestamp
 * }
 */
export const Tasks = new Mongo.Collection('tasks');

export const CATEGORIES = {
  Work:     { label: 'Work',     color: '#6366f1', icon: '💼' },
  Personal: { label: 'Personal', color: '#10b981', icon: '🏠' },
  Urgent:   { label: 'Urgent',   color: '#ef4444', icon: '🔥' },
  Other:    { label: 'Other',    color: '#f59e0b', icon: '📌' },
};

export const CATEGORY_LIST = Object.keys(CATEGORIES);
